name: infra-validate
on:
  workflow_call:
    inputs:
      working-directory: { type: string, default: "." }
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: tofu fmt -check -recursive
      - run: tofu init -backend=false
      - run: tofu validate
      - uses: terraform-linters/setup-tflint@v4
      - run: tflint --recursive
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.working-directory }}
